from pydantic import BaseModel, Field
import model_client as genai
from model_client import types
import utils
import re

client = genai.Client(api_key=utils.GOOGLE_API_KEY)

class Card(BaseModel):
    question: str = Field(description="卡片的问题部分")
    answer: str = Field(description="卡片的答案部分")
    id: str = Field(description="卡片的 Anki ID。新卡片必须为空字符串。原卡片保留原 ID。")

class DoctorResponse(BaseModel):
    cards: list[Card] = Field(description="根据讨论和笔记内容决定生成的全新原子化 Anki 卡片列表")

def handle(command, history, note_path, full_content):
    current_cards_dict = utils.parse_markdown_table(full_content)
    has_cards_section = bool(re.search(r'^## 卡片\s*$', full_content, re.MULTILINE))
    
    full_header, context_header, chat_content, related_body, _ = utils.parse_document(full_content)
    
    # Extract the target summary/digest content generated by dig.py with debouncing
    dig_content = ""
    # Search backwards for a model response containing level-3 headers, which is typical for @dig outputs
    for turn in reversed(history[:-1]):
        if turn["role"] == "model":
            text = turn["parts"][0].get("text", "")
            if "### " in text:
                dig_content = text
                break
                
    # Fallback: if no structured header is found, use the most recent model response
    if not dig_content:
        for turn in reversed(history[:-1]):
            if turn["role"] == "model":
                dig_content = turn["parts"][0].get("text", "")
                break
            
    if not dig_content.strip():
        return "⚠️ **AddNew Agent 提示**：在对话历史中未找到先前的总结内容。请先运行 `@dig` 生成知识总结短句，然后再运行 `@new` 进行制卡。"

    system_instruction = (
        "你是一个极其严谨且具备深厚教学诊断能力的 Anki 卡片制作专家。你的任务是**严格且仅根据**给出的【总结出的核心知识点】，提炼出高度原子化且最具核心考点价值的新卡片。\n\n"
        "【双重筛选制卡决策模型（单次完成）】\n"
        "给出的【总结出的核心知识点】是由三级标题和 bullet points 组成的。你必须严格按照以下步骤进行制卡：\n"
        "1. 逐条一一对应建卡：在大脑中首先针对给出的每一个 bullet point（子弹点）单独设计一张高度原子化的候选卡片。由于每一个 bullet point 在提炼时已经被设定为仅包含一个最微小的单一知识单元，因此你的每一张候选卡片必须与其完全精确对应，问题指向明确且答案极度简洁。\n"
        "2. 10% 核心筛选过滤：对上述设计的所有候选卡片进行严格审视，仅筛选并保留其中最核心、最具有考点和记忆价值的前 10%（若只有 1 张则保留 1 张，有多张则向上取整，例如总共 10 个子弹点对应 10 张候选卡片，最终仅返回最核心的 1 张）。主动过滤掉冗余、偏向常识或过于琐碎的卡片，确保产出少而精、极具含金量。\n"
        "3. 严禁超纲：严禁针对【总结出的核心知识点】之外的任何笔记背景、不相关的讨论或以前的类比故事进行制卡。\n\n"
        "【卡片生成黄金规则（必遵守）】\n"
        "- 极限原子化原则：被保留输出的每一张卡片只能测试一个不可再分的、最微小的单一知识单元。问题直接无歧义，答案极度简洁，通常只包含一个词或短语。\n"
        "- 去语境化 (Decontextualized)：卡片必须完全自包含。严禁在问题或答案中出现‘根据上述内容’、‘根据上面的对话’、‘正如刚才所说’等任何对当前上下文的指代词。\n"
        "- LaTeX 强制定界符：由于卡片直接呈现在 Obsidian 中，凡是属于科学、数学、化学等领域的变量、符号、公式、上下标，必须使用标准美元符号包裹！行内公式必须使用 $ ... $ 包裹（例如：$PP_i$，$Mg^{2+}$），块级公式必须使用 $$ ... $$ 包裹。绝对禁止使用 \\( ... \\) 或 \\[ ... \\]。\n\n"
        "【输出规范】\n"
        "请严格遵循 JSON Schema 返回 `cards` 列表。所有新卡片的 `id` 必须留空字符串 `\"\"`。\n\n"
        f"【总结出的核心知识点（必须以此为唯一制卡依据）】\n{dig_content}"
    )
    
    if context_header.strip():
        clean_header = context_header.strip()
        if clean_header.endswith("---"):
            clean_header = clean_header[:-3].strip()
        if clean_header:
            system_instruction += f"\n\n请参考以下当前笔记的正文内容来获取辅助的背景上下文，但卡片考点本身必须完全属于总结出的核心知识点范围：\n{clean_header}"

    last_user_idx = len(history) - 1
    original_text = history[last_user_idx]["parts"][0]["text"]

    history[last_user_idx]["parts"][0]["text"] = (
        f"{original_text}\n\n[系统注入] 请直接根据上述指定的【总结出的核心知识点】，根据【双重筛选制卡决策模型（单次完成）】进行制卡。所有新卡片的 id 必须为空字符串 \"\"。\n"
        f"注意：首先对给出的每一个 bullet point 单独设计一张最原子化的候选卡片，然后再进行严格筛选，仅返回最具核心考点价值的前 10% 核心卡片（向上取整，卡片少而精）。"
    )

    try:
        res = client.models.generate_content(
            model=utils.MODEL_NAME,
            contents=history,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                response_mime_type="application/json",
                response_schema=DoctorResponse,
                temperature=0.2
            )
        )
        parsed: DoctorResponse = res.parsed
        
        new_cards = []
        for card in parsed.cards:
            new_cards.append({
                "question": utils.unbold_text(card.question),
                "answer": utils.unbold_text(card.answer),
                "id": ""
            })
            
        if not new_cards:
            return "⚠️ **AddNew Agent 提示**：没有提炼出合适的新卡片。"

        # Strip the last user command block (the lines starting with > at the end of chat_content)
        lines = chat_content.rstrip().split('\n')
        last_quote_start = -1
        for i in range(len(lines) - 1, -1, -1):
            if lines[i].strip().startswith('>'):
                last_quote_start = i
            elif last_quote_start != -1:
                break
                
        if last_quote_start != -1:
            cleaned_chat_lines = lines[:last_quote_start]
            while cleaned_chat_lines and not cleaned_chat_lines[-1].strip():
                cleaned_chat_lines.pop()
            chat_content = '\n'.join(cleaned_chat_lines)

        # Absolutely preserve bold markers in the note and chat history
        cleaned_full_header = full_header
        cleaned_chat_content = chat_content

        # Combine all the new cards with existing ones
        current_cards_dict.extend(new_cards)
        
        # Build the updated content without the @addnew dialogue block
        base_body = f"{cleaned_full_header}{cleaned_chat_content}".rstrip()
        new_content = f"{base_body}\n\n"
        if related_body:
            new_content += f"{related_body.strip()}\n\n"
        
        new_table_block = "## 卡片\n\n" + utils.format_cards_to_table(current_cards_dict) + "\n"
        new_content += new_table_block
        
        # Write back to the file
        with open(note_path, 'w', encoding='utf-8') as f:
            f.write(new_content)
            
        if has_cards_section:
            print(f"✅ [AddNew Agent] Successfully appended {len(new_cards)} new cards to the existing cards table.")
        else:
            print(f"✅ [AddNew Agent] Successfully created a new cards table with {len(new_cards)} cards.")
            
        return None  # Return None to prevent router.py from inserting any AI response

    except Exception as e:
        return f"❌ **AddNew Agent 发生错误**: {e}"
